# Setup
title:               MOPy
tagline:             'Learn Orbital Mechanics visually'
description:         'This is an application to learn Orbital Mechanics in a fun and interesting way. You do not require any prior knowledge to get started with it. You can download and get started with it directly.'
url:                 https://mechanics-of-orbit.github.io/getMOPy
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
